general {
    hide_cursor = true
    immediate_render = true
    disable_loading_bar = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgba(0,0,0,1.0)
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill
    outer_color = rgba(0, 0, 0, 0)
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = 󰌾 Logged in as $USER
    fail_text = $PAMFAIL$FPRINTFAIL
    dots_spacing = 0.2
    position = 0, -20
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d - %H:%M")"
    font_size = 15
    font_family = JetBrainsMono Nerd Font
    position = 0, 500
    halign = center
    valign = center
}
